version: '2'
services:
    api:
        build: .
        depends_on:
            - mongo
        links:
            - mongo
        environment:
            NODE_ENV: development
            MONGO_URL: mongodb://mongo/database
        ports:
            - "3002:3002"
        volumes:
            - ""
            - ""
        entrypoint: "yarn run watch"

    mongo:
        image: mongo
